---

info:
  description: Training configuration repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:ahardpassword@eurekaserver-ungodlike-overnourishment.cfapps.io/eureka
---

spring:
  profiles: cloud

eureka.instance.hostname: ${vcap.application.application_uris[0]}
eureka.instance.nonSecurePort: 80